### ISSUE TITLE
Trying to open a PR throws error

### ISSUE THREAD

**Issue by dlvhdr** [nvim-telescope/telescope-ui-select.nvim#14]
Not sure, but I think the plugin got stuck on fetching contributors (`⣷ fetching repository contributors`). It's my company's private repo, so maybe it times out because of too many contributors.
The error I get is: 

```
Error executing luv callback:
...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:68: Expected the end but found T_ARR_BEGIN at character 100610
stack traceback:
        [C]: in function 'decode'
        ...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:68: in function <...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:59>
```

**Comment by Conni2461** [comment]
I think you have opened this in the wrong repository. This has nothing to do with `gh.nvim`. 

If it does you need to explain in what way this is related because currently i dont get it.

This repo is about `vim.ui.select`

**Comment by dlvhdr** [comment]
Whoops my bad, sorry
