### ISSUE TITLE
Nerd font not working

### ISSUE THREAD

**Issue by dlvhdr** [nvim-telescope/telescope-ui-select.nvim#15]
I'm using FiraCode with Alacritty (terminal emulator) in tmux and the icons don't display properly.
![image](https://user-images.githubusercontent.com/6196971/167309722-91447e41-38f8-4f17-9b9d-ed0e0ea8cdb1.png)

**Comment by Conni2461** [comment]
Similar to #14 I think you've opened this in the wrong repo

We dont display any unicodes. I think your installed font doesnt have nerd font patches: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode
