### ISSUE TITLE
Help me with configuration

### ISSUE THREAD

**Issue by MitaiDart** [nvim-telescope/telescope-ui-select.nvim#17]
Help the noob with the configuration of your plugin and
nvim-lightbulb, copied the code from the README, but when entering the command `:lua vm.ls.buf.code_action()` telescope-ui-select does not work, what else do I need to write?
![Снимок экрана от 2022-11-21 22-50-50](https://user-images.githubusercontent.com/104931116/203222253-23856559-55a7-4c08-8c0c-26c476afe84a.png)

**Comment by MitaiDart** [comment]
copied the configuration from [JafarAbdi](https://github.com/JafarAbdi)
`-- Telescope
local dropdown_configs = {
  layout_strategy = "vertical",
  layout_config = {
    prompt_position = "bottom",
    vertical = {
      width = 0.8,
      height = 100,
    },
  },
}

require("telescope").setup({
  defaults = require("telescope.themes").get_dropdown(dropdown_configs),
})

require("telescope").setup({
  extensions = {
    ["ui-select"] = {
      require("telescope.themes").get_dropdown(dropdown_configs),
    },
  },`
  but still the output goes through the native part...

**Comment by JafarAbdi** [comment]
The link you shared redirects to this repo, could you please share a minimal reproducible example?

I wonder if you forgot to load the extension.

```lua
require("telescope").load_extension("ui-select")
```

**Comment by MitaiDart** [comment]
full config telescop
```-- Telescope
local dropdown_configs = {
  layout_strategy = "vertical",
  layout_config = {
    prompt_position = "bottom",
    vertical = {
      width = 0.8,
      height = 100,
    },
  },
}

require("telescope").setup({
  defaults = require("telescope.themes").get_dropdown(dropdown_configs),
})

require("telescope").setup {
  extensions = {
    ["ui-select"] = {
      require("telescope.themes").get_dropdown {
        dropdown_configs
      }
    }
  }
}
require("telescope").load_extension("ui-select")
require("telescope").load_extension("flutter")```

packer
```
-- Telescope
  use {
    'nvim-telescope/telescope.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope-ui-select.nvim' },
    config = function()
      require('telescope')
    end
  }
```

**Comment by MitaiDart** [comment]
[https://github.com/MitaiDart/dotfiles/tree/master/nvim](url)

**Comment by MitaiDart** [comment]
https://github.com/MitaiDart/dotfiles/tree/master/nvim

**Comment by MitaiDart** [comment]
> full config telescop
> 
> ```
> local dropdown_configs = {
>   layout_strategy = "vertical",
>   layout_config = {
>     prompt_position = "bottom",
>     vertical = {
>       width = 0.8,
>       height = 100,
>     },
>   },
> }
> 
> require("telescope").setup({
>   defaults = require("telescope.themes").get_dropdown(dropdown_configs),
> })
> 
> require("telescope").setup {
>   extensions = {
>     ["ui-select"] = {
>       require("telescope.themes").get_dropdown {
>         dropdown_configs
>       }
>     }
>   }
> }
> require("telescope").load_extension("ui-select")
> require("telescope").load_extension("flutter")
> ```
> 
> packer
> 
> ```
> -- Telescope
>   use {
>     'nvim-telescope/telescope.nvim',
>     requires = {
>       'nvim-lua/plenary.nvim',
>       'nvim-telescope/telescope-ui-select.nvim' },
>     config = function()
>       require('telescope')
>     end
>   }
> ```
> 
> NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3

**Comment by MitaiDart** [comment]
> Ссылка, которой вы поделились, перенаправляет на этот репозиторий, не могли бы вы поделиться минимальным воспроизводимым примером?
> 
> Интересно, не забыли ли вы загрузить расширение.
> 
> ```lua
> требуется ("телескоп").load_extension("ui-select")
> ```

full config telescop

local dropdown_configs = {
  layout_strategy = "vertical",
  layout_config = {
    prompt_position = "bottom",
    vertical = {
      width = 0.8,
      height = 100,
    },
  },
}

require("telescope").setup({
  defaults = require("telescope.themes").get_dropdown(dropdown_configs),
})

require("telescope").setup {
  extensions = {
    ["ui-select"] = {
      require("telescope.themes").get_dropdown {
        dropdown_configs
      }
    }
  }
}
require("telescope").load_extension("ui-select")
require("telescope").load_extension("flutter")
packer

-- Telescope
  use {
    'nvim-telescope/telescope.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope-ui-select.nvim' },
    config = function()
      require('telescope')
    end
  }
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by Conni2461** [comment]
Looking at your dots it seems like you want
```lua
-- Telescope
  use {
    'nvim-telescope/telescope.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope-ui-select.nvim' },
    config = function()
      require('plugins.telescope') -- you forgot the module here
    end
  }
```

**Comment by MitaiDart** [comment]
> Глядя на ваши точки, кажется, что вы хотите
> 
> ```lua
> используйте--
>    Telescope {
>  'nvim-telescope/telescope.nvim',
> требуется = {
>  'nvim-lua/plenary.nvim', 
> 'nvim-телескоп / телескоп-ui-select.nvim' },
> config = функция ()
>  требуется ('плагины.телескоп') -- вы забыли, что ваш модуль находится в каталоге плагинов, здесь
>      конец
> }
> ```

everything works thank you very much))
