### ISSUE TITLE
Code actions failing in Neovim version: v0.10.0-dev-6823fdb

### ISSUE THREAD

**Issue by JulienLecoq** [nvim-telescope/telescope-ui-select.nvim#29]
When attempting to call: ``vim.lsp.buf.code_action()``.

I get the following error:

```
Error executing vim.schedule lua callback: ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:33: attempt to index field 'ctx' (a nil value)
stack traceback:
        ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:33: in function <...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:23>
        ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:106: in function 'select'
        .../local/nvim-macos/share/nvim/runtime/lua/vim/lsp/buf.lua:687: in function 'on_code_action_results'
        .../local/nvim-macos/share/nvim/runtime/lua/vim/lsp/buf.lua:703: in function 'handler'
        /usr/local/nvim-macos/share/nvim/runtime/lua/vim/lsp.lua:2201: in function 'handler'
        /usr/local/nvim-macos/share/nvim/runtime/lua/vim/lsp.lua:1505: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by Conni2461** [comment]
on which neovim version do you see this error?

**Comment by Conni2461** [comment]
oh my bad, overlooked that.

Yeah but that makes this issue easy. version is no longer support by telescope.

> [Neovim (v0.9.0)](https://github.com/neovim/neovim/releases/tag/v0.9.0) or the latest neovim nightly commit is required for telescope.nvim to work.

I am not interested in supporting old nightly builds. sorry 

You shouldn't have any issues if you use https://github.com/neovim/neovim/commit/9281edb334a374e7753d4a6b7a05e31120e39772 or newer or you use a stable 0.9.* version
