### ISSUE TITLE
Opening the selector from Visual-mode, I can not input text to filter values

### ISSUE THREAD

**Issue by kyoh86** [nvim-telescope/telescope-ui-select.nvim#3]
Like a `vim.lsp.buf.range_code_action()`, some features may be called from the Visual-mode.
When I called them with this plugin from Visual-mode, keeping the mode, so I cannot input text to filter choices.

**Comment by Conni2461** [comment]
Should probably be fixed from telescope side :thinking:

**Comment by Conni2461** [comment]
We recently merged a PR that fixed opening telescope from visual mode. 

Closing if it still doesnt work feel free to reopen :)
