### ISSUE TITLE
BUG: on_choice is called twice

### ISSUE THREAD

**Issue by alfaix** [nvim-telescope/telescope-ui-select.nvim#38]
Hello,

First of all thanks a lot for the awesome plugin :) It's a small but very sweet UI improvement - I love things like this!

I believe [this](https://github.com/nvim-telescope/telescope-ui-select.nvim/commit/c261d903a78c2cda47a5e44488621f10f9dd7fcf) commit introduced a regression. If I choose something, `on_choice` is called twice. I don't have a minimal_init, but you can probably try it with your own init. To reproduce, run this little script:

```lua
vim.ui.select({"a", "b", "c"}, {}, function(item, idx) vim.notify(vim.inspect({item, idx})) end)
```
And then select any item.

What you will see is two notifications, `{}` and the actual choice. I believe it's because actions.close is called even in case I actually selected something. This introduces some hard-to-track issues in code that is using vim.ui.select.

**Comment by Conni2461** [comment]
you are right, sorry my bad. https://github.com/nvim-telescope/telescope-ui-select.nvim/pull/39 should fix your issue. can you confirm?

**Comment by alfaix** [comment]
Yes, that fixes it, thanks!
