### ISSUE TITLE
Code action: `expected string, got function`

### ISSUE THREAD

**Issue by hejops** [nvim-telescope/telescope-ui-select.nvim#44]
Minimal config (as per README):
```lua
local telescope = require("telescope")
telescope.setup({
	extensions = {
		["ui-select"] = {
			require("telescope.themes").get_dropdown(
				-- { initial_mode = "normal" } -- optional
			),

		},
	},
})
telescope.load_extension("ui-select")
```

Then, in some language/file/line with support for code actions (e.g. Go), call:
```
:lua vim.lsp.buf.code_action()
```

The following error is produced, regardless of `initial_mode` value:

```text
E5108: Error executing lua: vim/shared.lua:0: s: expected string, got function
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:162: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:262: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:261>
```

**Comment by mikew** [comment]
Also seeing this on nvim 0.10.1. Curious what you mean when you say "from insert mode". Do you mean insert mode of the file, or Telescope's input field? Because I'm seeing it regardless of either.


https://github.com/user-attachments/assets/8ea9a327-5ed7-4788-a04b-3f505cd7d07f

**Comment by hejops** [comment]
Thanks for confirming. I forgot I had filed this issue since it was so long ago, and I stopped using this plugin since I never found a compelling use case for it, outside of code actions (which I'm not a regular user of).

In any case, after checking it out again, the previously observed error still occurs, regardless of which mode `vim.lsp.buf.code_action` was invoked in (normal/insert), and the value of `initial_mode`.

From grokking the source of [`code_action`](https://github.com/neovim/neovim/blob/615f7bbff06c0585aacce542fac4bc823070ebee/runtime/lua/vim/lsp/buf.lua#L846), I think it returns a table of `vim.lsp.CodeActionResultEntry`, but `ui-select` expects a table of `string`, resulting in the error.

**Comment by hejops** [comment]
@mikew I came across the [tiny-code-action](https://github.com/rachartier/tiny-code-action.nvim) plugin which presents code actions in telescope and applies them to the workspace correctly.

(There is also [actions-preview](https://github.com/aznhe21/actions-preview.nvim) but IME it doesn't apply the action properly, producing the error described here)

I think there is probably no issue with `telescope-ui-select`, so I'll close this.
