### ISSUE TITLE
`:lua vim.lsp.buf.code_action()` doesn't show LSP client name

### ISSUE THREAD

**Issue by axieax** [nvim-telescope/telescope-ui-select.nvim#6]
Using the configuration provided by the README setup, I want the Telescope picker to also display the LSP client name, as in the demo image. 

![image](https://user-images.githubusercontent.com/62098008/164776863-90a4994f-302e-4177-95a3-9229c6fe135c.png)

Although I normally use dressing.nvim for my `vim.ui.select` customisations, I currently use Telescope's built-in code actions just for how it formats the LSP client name (doesn't look as great in [dressing.nvim](https://github.com/stevearc/dressing.nvim/issues/6) unfortunately since it doesn't support columns).

**Comment by Conni2461** [comment]
Working on it, already got it working:

![image](https://user-images.githubusercontent.com/15233006/164785406-5a89c243-e062-4f65-b133-dd85e3080b25.png)

Just not happy with the abstraction. It will be done before `lsp_code_action` is removed

**Comment by Conni2461** [comment]
Proposed fix #7 

Testers appreciated :)
